### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by sha-lou** [brickspert/react-family-ie8#5]
![image](https://user-images.githubusercontent.com/33541084/35792570-cb23dc94-0a88-11e8-8d02-5ac714c40999.png)

npm start 后，报错，见上图，我下载了你的文件，按照npm install正常，但start出错

**Comment by brickspert** [comment]
@sha-lou  你8080端口被占用了，你换个端口

**Comment by sha-lou** [comment]
请问下你的这个项目换端口的代码在哪

**Comment by sha-lou** [comment]
哦，我已经解决了，感谢
